version: '1.29.2'
services:

    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: 'laravel-app'
        container_name: laravel-app
        ports:
            - 8000:8000
        volumes:
            - ./:/var/www/html


    # php:
    #     build:
    #         context: .
    #     # dockerfile: Dockerfile
    #     volumes:
    #         - .demo-app/:/var/www/html/demo-app
    #     ports:
    #         - 8080:80
    #     depends_on:

    db:
        image: mysql:latest
        restart: always
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: Root@123
            MYSQL_DATABASE: demo-app
            MYSQL_USER: root
            MYSQL_PASSWORD: Root@123
        volumes:
            - ./db:/var/lib/mysql

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        ports:
            - 3400:80
        depends_on:
            - db

    redis:
        image: redis:latest
        container_name: app_redis
        ports:
            - "6379:6379"

    s3:
        image: quay.io/minio/minio:RELEASE.2022-08-13T21-54-44Z
        command: minio server /data
        ports:
        - "9000:9000"
        environment:
            MINIO_ROOT_USER: minio
            MINIO_ROOT_PASSWORD: minio123
            MINIO_ACCESS_KEY: minio_access_key
            MINIO_SECRET_KEY: minio_secret_key
        restart: always
