version: '3'
services:
    web:
        build:
            context: .
            dockerfile: Dockerfile
        command: 'php artisan serve --host=127.0.0.1'
        ports:
            - "8080:80"
        volumes:
            - .:/var/www/html/php-laravel-demo
        depends_on:
            - db
            - redis
            - minio

    queue:
        container_name: Queue
        build:
            context: .
            dockerfile: Dockerfile
        command: 'php artisan queue:restart && php artisan queue:work'
        depends_on:
            - db

    db:
        image: mysql:5.7
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: laravel_db
            MYSQL_USER: root
            MYSQL_PASSWORD: root
        ports:
            - "3366:3366"
        volumes:
            - db_data:/var/lib/mysql

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links:
            - db
        ports:
            - "8081:80"
        environment:
            PMA_HOST: db
            MYSQL_ROOT_PASSWORD: root

    redis:
        image: redis:latest
        ports:
            - "6379:6379"

    minio:
        image: minio/minio
        command: server /data --console-address ":9001"
        environment:
            MINIO_ACCESS_KEY: minioaccesskey
            MINIO_SECRET_KEY: miniosecretkey
            MINIO_ROOT_USER: minio
            MINIO_ROOT_PASSWORD: minio123
        ports:
            - "9000:9000"
            - '9001:9001'
        healthcheck:
            test:
                [
                    "CMD",
                    "curl",
                    "-f",
                    "http://localhost:9000/minio/health/live"
                ]
            interval: 30s
            timeout: 20s
            retries: 3
        volumes:
            - minio_data:/data

    maildev:
        image: maildev/maildev
        ports:
            - "8025:1080"

volumes:
    db_data:
    minio_data:
