version: '3.3'
services:

    app:
        container_name: serve
        build:
            context: .
            dockerfile: Dockerfile
        command: 'php artisan serve --host=127.0.0.1'
        ports:
            - 8000:8000
        volumes:
            - .:/var/www/html/php-laravel-demo

    queue:
        container_name: Queue
        build:
            context: .
            dockerfile: Dockerfile
        command: 'php artisan queue:work'
        depends_on:
            - db

    db:
        image: mysql:latest
        container_name: Database
        restart: always
        environment:
            MYSQL_DATABASE: php_demo_laravel
            MYSQL_USER: root
            MYSQL_ROOT: "root"
            MYSQL_PASSWORD: root
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - db:/var/lib/mysql
        ports:
            - 3306:3306

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        links:
            - db
        environment:
            PMA_HOST: db
            PMA_PORT: 3306
            PMA_ARBITRARY: 1
        restart: always
        ports:
            - 3400:80
        depends_on:
            - db

    redis:
        image: redis:latest
        container_name: app_redis
        ports:
            - "6379:6379"

    s3:
        image: quay.io/minio/minio:RELEASE.2022-08-13T21-54-44Z
        container_name: s3_minio
        command: minio server /data
        ports:
            - "9000:9000"
        environment:
            MINIO_ROOT_USER: minio
            MINIO_ROOT_PASSWORD: minio123
            MINIO_ACCESS_KEY: minio_access_key
            MINIO_SECRET_KEY: minio_secret_key
        restart: always

    mail:
        hostname: maildev
        container_name: mail
        command: bin/maildev --web 1080 --smtp 1025 --mail-directory /home/maildev/data
        volumes:
            - ./var/data/maildev:/home/maildev/data
        ports:
            - "1080:1080"
            - "1025:1025"
        networks:
            - laravel-exa

    networks:
        laravel-exa:
            driver: bridge

    volumes:
        db:
            driver: local
